
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action Action;

	private global::Gtk.Action ConnectAction;

	private global::Gtk.Action DisconnectAction;

	private global::Gtk.Action MANPagesAction;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.Button button2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.Action = new global::Gtk.Action("Action", global::Mono.Unix.Catalog.GetString("?"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString("?");
		w1.Add(this.Action, null);
		this.ConnectAction = new global::Gtk.Action("ConnectAction", global::Mono.Unix.Catalog.GetString("Connect"), null, null);
		this.ConnectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Connect");
		w1.Add(this.ConnectAction, null);
		this.DisconnectAction = new global::Gtk.Action("DisconnectAction", global::Mono.Unix.Catalog.GetString("Disconnect"), null, null);
		this.DisconnectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Disconnect");
		w1.Add(this.DisconnectAction, null);
		this.MANPagesAction = new global::Gtk.Action("MANPagesAction", global::Mono.Unix.Catalog.GetString("MAN pages"), null, null);
		this.MANPagesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("MAN pages");
		w1.Add(this.MANPagesAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DestroyWithParent = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='ConnectAction' action='ConnectAction'/><menuitem name='DisconnectAction' action='DisconnectAction'/></menu><menu name='EditAction' action='EditAction'/><menu name='Action' action='Action'/></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
		this.menubar2.WidthRequest = 0;
		this.menubar2.Name = "menubar2";
		this.fixed1.Add(this.menubar2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.menubar2]));
		w2.X = 11;
		w2.Y = 7;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Xalign = 0F;
		this.button2.Yalign = 0F;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("_OK");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w3.X = 771;
		w3.Y = 10;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1030;
		this.DefaultHeight = 581;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
